version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: web
      SPRING_DATASOURCE_PASSWORD: 'cdf90031-bfa4-4aa0'
    networks:
      - healthcheck_network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - healthcheck_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: web
      POSTGRES_PASSWORD: 'cdf90031-bfa4-4aa0'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - healthcheck_network

networks:
  healthcheck_network:
    driver: bridge

volumes:
  db_data:

